{"name": "Проверка, что если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "start": 1737302857814, "stop": 1737302858296, "uuid": "665a6bf1-8236-4721-85bd-e2f4f4f23621", "historyId": "05f0c878354b348fa068616c75569e18", "testCaseId": "05f0c878354b348fa068616c75569e18", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_duplicate_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "MacBook-Air-Maksim.local"}, {"name": "thread", "value": "9750-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}